{
    "fixes": [
        "/home/runner/work/app_calculate_fuel_consumption_android/app_calculate_fuel_consumption_android>/::"
    ],
    "codecov": {
        "disable_default_path_fixes": true
    }
}
